"""Claude Agent SDK compilation target."""

from __future__ import annotations

import json

from ..compiler import compile_system_prompt
from ..models import AgentSpec
from ..network.mcp import generate_mcp_client_code
from .base import CompilationTarget, OutputFile


class ClaudeSDKTarget(CompilationTarget):
    name = "claude-sdk"
    description = "Runnable Python project using the Claude Agent SDK (Anthropic)"

    def compile(self, spec: AgentSpec) -> list[OutputFile]:
        return [
            self._generate_agent(spec),
            self._generate_requirements(spec),
            self._generate_test(spec),
        ]

    def _generate_agent(self, spec: AgentSpec) -> OutputFile:
        prompt = compile_system_prompt(spec, "claude-sonnet-4")
        prompt_escaped = prompt.replace('\\', '\\\\').replace('"""', '\\"\\"\\"')

        lines: list[str] = []
        lines.append(f'"""Agent: {spec.agent.name} — Generated by Cortex Protocol v0.1"""')
        lines.append("")
        lines.append("import anthropic")
        lines.append("")
        lines.append("")
        lines.append("# ── Configuration ────────────────────────────────────────────────────")
        lines.append("")
        lines.append(f'MODEL = "{spec.model.preferred}"')
        lines.append(f'SYSTEM_PROMPT = """{prompt_escaped}"""')
        lines.append("")

        # Build TOOLS list
        lines.append("TOOLS = [")
        for tool in spec.tools:
            input_schema = {
                "type": "object",
                "properties": tool.parameters.properties,
                "required": tool.parameters.required,
            }
            schema_json = json.dumps(input_schema, indent=8)
            # Indent each line of the schema
            schema_lines = schema_json.split("\n")
            lines.append("    {")
            lines.append(f'        "name": "{tool.name}",')
            lines.append(f'        "description": "{tool.description}",')
            lines.append(f'        "input_schema": {schema_lines[0]}')
            for sl in schema_lines[1:]:
                lines.append(f"        {sl}")
            # Close the previous line properly
            lines[-1] = lines[-1].rstrip()
            lines.append("    },")
        lines.append("]")
        lines.append("")
        lines.append("")

        # MCP setup block if any tools use MCP
        mcp_tools = [t for t in spec.tools if t.mcp]
        if mcp_tools:
            lines.append("# ── MCP Setup ────────────────────────────────────────────────────────")
            lines.append("")
            seen_servers: set[str] = set()
            for tool in mcp_tools:
                mcp_code = generate_mcp_client_code("claude-sdk", tool.name, tool.mcp)
                lines.append(mcp_code["setup"])
                lines.append("")

        # Build tool handlers
        lines.append("# ── Tool Handlers ────────────────────────────────────────────────────")
        lines.append("")

        handler_names: list[str] = []
        for tool in spec.tools:
            func_name = _to_snake(tool.name)
            handler_name = f"handle_{func_name}"
            handler_names.append(handler_name)

            if tool.mcp:
                mcp_code = generate_mcp_client_code("claude-sdk", tool.name, tool.mcp)
                for call_line in mcp_code["call"].split("\n"):
                    lines.append(call_line)
                lines.append("")
                lines.append("")
            else:
                lines.append(f"def {handler_name}(tool_input: dict) -> str:")
                lines.append(f'    """{tool.description}"""')
                for pname in tool.parameters.properties:
                    lines.append(f'    {pname} = tool_input.get("{pname}")')
                lines.append(f"    # TODO: Implement {tool.name}")
                lines.append(f'    return "{tool.name} executed"')
                lines.append("")
                lines.append("")

        # Build dispatch map
        lines.append("TOOL_DISPATCH = {")
        for tool in spec.tools:
            func_name = _to_snake(tool.name)
            lines.append(f'    "{tool.name}": handle_{func_name},')
        lines.append("}")
        lines.append("")
        lines.append("")

        # Build agent loop
        max_turns = spec.policies.max_turns or 10
        lines.append("# ── Agent Loop ───────────────────────────────────────────────────────")
        lines.append("")
        lines.append(f"def run_agent(user_message: str, max_turns: int = {max_turns}) -> str:")
        lines.append('    """Run the agent in an agentic loop with tool use."""')
        lines.append("    client = anthropic.Anthropic()")
        lines.append('    messages = [{"role": "user", "content": user_message}]')
        lines.append("")
        lines.append("    for turn in range(max_turns):")
        lines.append("        response = client.messages.create(")
        lines.append("            model=MODEL,")
        lines.append("            max_tokens=4096,")
        lines.append("            system=SYSTEM_PROMPT,")
        lines.append("            tools=TOOLS,")
        lines.append("            messages=messages,")
        lines.append("        )")
        lines.append("")
        lines.append('        if response.stop_reason == "tool_use":')
        lines.append("            tool_results = []")
        lines.append("            for block in response.content:")
        lines.append('                if block.type == "tool_use":')
        lines.append("                    handler = TOOL_DISPATCH.get(block.name)")
        lines.append("                    if handler:")
        lines.append("                        result = handler(block.input)")
        lines.append("                    else:")
        lines.append('                        result = f"Unknown tool: {block.name}"')
        lines.append("                    tool_results.append({")
        lines.append('                        "type": "tool_result",')
        lines.append('                        "tool_use_id": block.id,')
        lines.append('                        "content": result,')
        lines.append("                    })")
        lines.append("")
        lines.append('            messages.append({"role": "assistant", "content": response.content})')
        lines.append('            messages.append({"role": "user", "content": tool_results})')
        lines.append("        else:")
        lines.append("            for block in response.content:")
        lines.append('                if hasattr(block, "text"):')
        lines.append("                    return block.text")
        lines.append('            return ""')
        lines.append("")
        lines.append('    return "Max turns reached without final response."')
        lines.append("")
        lines.append("")
        lines.append('if __name__ == "__main__":')
        lines.append('    result = run_agent("Hello, what can you do?")')
        lines.append("    print(result)")
        lines.append("")

        return OutputFile(
            path="agent.py",
            content="\n".join(lines),
            description="Claude Agent SDK agent with tool definitions and agentic loop",
        )

    def _generate_requirements(self, spec: AgentSpec) -> OutputFile:
        return OutputFile(
            path="requirements.txt",
            content="anthropic>=0.40\n",
            description="Python dependencies",
        )

    def _generate_test(self, spec: AgentSpec) -> OutputFile:
        lines: list[str] = []
        lines.append(f'"""Tests for {spec.agent.name} — Generated by Cortex Protocol v0.1"""')
        lines.append("")
        lines.append("from agent import TOOLS, TOOL_DISPATCH, SYSTEM_PROMPT, MODEL")
        lines.append("")
        lines.append("")
        lines.append("def test_system_prompt_not_empty():")
        lines.append("    assert len(SYSTEM_PROMPT) > 0")
        lines.append("")
        lines.append("")
        lines.append("def test_model_configured():")
        lines.append(f'    assert MODEL == "{spec.model.preferred}"')
        lines.append("")
        lines.append("")
        lines.append("def test_tools_defined():")
        lines.append(f"    assert len(TOOLS) == {len(spec.tools)}")
        lines.append('    tool_names = {t["name"] for t in TOOLS}')
        for t in spec.tools:
            lines.append(f'    assert "{t.name}" in tool_names')
        lines.append("")
        lines.append("")
        lines.append("def test_tool_dispatch_complete():")
        lines.append("    for tool in TOOLS:")
        lines.append('        assert tool["name"] in TOOL_DISPATCH, f"Missing handler for {tool[\'name\']}"')
        lines.append("")

        return OutputFile(
            path="test_agent.py",
            content="\n".join(lines),
            description="Test stubs for the generated Claude agent",
        )


def _to_snake(name: str) -> str:
    return name.lower().replace("-", "_").replace(" ", "_")
