"""CrewAI compilation target."""

from __future__ import annotations

import yaml

from ..models import AgentSpec
from .base import CompilationTarget, OutputFile


class CrewAITarget(CompilationTarget):
    name = "crewai"
    description = "CrewAI YAML configs (agents.yaml, tasks.yaml) and crew.py scaffold"

    def compile(self, spec: AgentSpec) -> list[OutputFile]:
        return [
            self._generate_agents_yaml(spec),
            self._generate_tasks_yaml(spec),
            self._generate_crew_py(spec),
            self._generate_requirements(spec),
            self._generate_test(spec),
        ]

    def _generate_agents_yaml(self, spec: AgentSpec) -> OutputFile:
        agent_key = _to_snake(spec.agent.name)

        backstory_parts = [spec.agent.instructions.strip()]
        if spec.policies.forbidden_actions:
            backstory_parts.append(
                "You must NEVER: " + "; ".join(spec.policies.forbidden_actions)
            )
        if spec.policies.escalation.trigger:
            backstory_parts.append(
                f"Escalation: When {spec.policies.escalation.trigger}, "
                f"hand off to {spec.policies.escalation.target}."
            )

        agent_def = {
            agent_key: {
                "role": spec.agent.name,
                "goal": spec.agent.description,
                "backstory": "\n".join(backstory_parts),
                "tools": [t.name for t in spec.tools],
                "verbose": True,
                "allow_delegation": False,
            }
        }

        if spec.policies.max_turns:
            agent_def[agent_key]["max_iter"] = spec.policies.max_turns

        return OutputFile(
            path="config/agents.yaml",
            content=yaml.dump(agent_def, default_flow_style=False, sort_keys=False),
            description="CrewAI agent configuration",
        )

    def _generate_tasks_yaml(self, spec: AgentSpec) -> OutputFile:
        agent_key = _to_snake(spec.agent.name)

        task_def = {
            f"{agent_key}_task": {
                "description": (
                    f"Execute the primary objective of {spec.agent.name}: "
                    f"{spec.agent.description}"
                ),
                "expected_output": "A clear, structured result addressing the objective.",
                "agent": agent_key,
            }
        }

        for tool in spec.tools:
            tool_key = _to_snake(tool.name)
            task_def[f"{tool_key}_task"] = {
                "description": tool.description,
                "expected_output": f"Result from {tool.name} execution.",
                "agent": agent_key,
                "tools": [tool.name],
            }

        return OutputFile(
            path="config/tasks.yaml",
            content=yaml.dump(task_def, default_flow_style=False, sort_keys=False),
            description="CrewAI task configuration",
        )

    def _generate_crew_py(self, spec: AgentSpec) -> OutputFile:
        agent_key = _to_snake(spec.agent.name)
        class_name = _to_pascal(spec.agent.name)

        lines: list[str] = []
        lines.append(f'"""Crew: {spec.agent.name} — Generated by Cortex Protocol v0.1"""')
        lines.append("")
        lines.append("from crewai import Agent, Crew, Process, Task")
        lines.append("from crewai.project import CrewBase, agent, crew, task")

        if spec.tools:
            tool_classes = ", ".join(_to_pascal(t.name) + "Tool" for t in spec.tools)
            lines.append("")
            lines.append(f"# TODO: Import or define your custom tools")
            lines.append(f"# from tools import {tool_classes}")

        lines.append("")
        lines.append("")
        lines.append("@CrewBase")
        lines.append(f"class {class_name}Crew:")
        lines.append(f'    """{spec.agent.description}"""')
        lines.append("")
        lines.append('    agents_config = "config/agents.yaml"')
        lines.append('    tasks_config = "config/tasks.yaml"')
        lines.append("")

        lines.append("    @agent")
        lines.append(f"    def {agent_key}(self) -> Agent:")
        lines.append(f'        return Agent(config=self.agents_config["{agent_key}"])')
        lines.append("")

        lines.append("    @task")
        lines.append(f"    def {agent_key}_task(self) -> Task:")
        lines.append(f'        return Task(config=self.tasks_config["{agent_key}_task"])')
        lines.append("")

        lines.append("    @crew")
        lines.append("    def crew(self) -> Crew:")
        lines.append("        return Crew(")
        lines.append("            agents=self.agents,")
        lines.append("            tasks=self.tasks,")
        lines.append("            process=Process.sequential,")
        lines.append("            verbose=True,")
        lines.append("        )")
        lines.append("")
        lines.append("")
        lines.append('if __name__ == "__main__":')
        lines.append(f"    result = {class_name}Crew().crew().kickoff(")
        lines.append('        inputs={"topic": "Hello, what can you do?"}')
        lines.append("    )")
        lines.append("    print(result)")
        lines.append("")

        return OutputFile(
            path="crew.py",
            content="\n".join(lines),
            description="CrewAI crew scaffold",
        )

    def _generate_requirements(self, spec: AgentSpec) -> OutputFile:
        return OutputFile(
            path="requirements.txt",
            content="crewai>=0.80\ncrewai-tools>=0.14\n",
            description="Python dependencies",
        )

    def _generate_test(self, spec: AgentSpec) -> OutputFile:
        agent_key = _to_snake(spec.agent.name)

        lines: list[str] = []
        lines.append(f'"""Tests for {spec.agent.name} CrewAI config — Generated by Cortex Protocol v0.1"""')
        lines.append("")
        lines.append("import yaml")
        lines.append("")
        lines.append("")
        lines.append("def test_agents_yaml_valid():")
        lines.append('    with open("config/agents.yaml") as f:')
        lines.append("        data = yaml.safe_load(f)")
        lines.append(f'    assert "{agent_key}" in data')
        lines.append(f'    assert data["{agent_key}"]["role"] == "{spec.agent.name}"')
        lines.append("")
        lines.append("")
        lines.append("def test_tasks_yaml_valid():")
        lines.append('    with open("config/tasks.yaml") as f:')
        lines.append("        data = yaml.safe_load(f)")
        lines.append(f'    assert "{agent_key}_task" in data')
        lines.append(f'    assert data["{agent_key}_task"]["agent"] == "{agent_key}"')
        lines.append("")
        lines.append("")
        lines.append("def test_agent_has_tools():")
        lines.append('    with open("config/agents.yaml") as f:')
        lines.append("        data = yaml.safe_load(f)")
        lines.append(f'    tools = data["{agent_key}"].get("tools", [])')
        lines.append(f"    assert len(tools) == {len(spec.tools)}")
        lines.append("")

        return OutputFile(
            path="test_crew.py",
            content="\n".join(lines),
            description="Test stubs for CrewAI configuration",
        )


def _to_snake(name: str) -> str:
    return name.lower().replace("-", "_").replace(" ", "_")


def _to_pascal(name: str) -> str:
    return "".join(w.capitalize() for w in name.replace("-", " ").replace("_", " ").split())
