"""LangGraph compilation target."""

from __future__ import annotations

from ..compiler import compile_system_prompt
from ..models import AgentSpec
from .base import CompilationTarget, OutputFile


class LangGraphTarget(CompilationTarget):
    name = "langgraph"
    description = "LangGraph StateGraph skeleton with tools and human-in-the-loop"

    def compile(self, spec: AgentSpec) -> list[OutputFile]:
        return [
            self._generate_graph(spec),
            self._generate_requirements(spec),
            self._generate_test(spec),
        ]

    def _generate_graph(self, spec: AgentSpec) -> OutputFile:
        prompt = compile_system_prompt(spec, "gpt-4o")
        # Escape for embedding in triple-quoted string
        prompt_escaped = prompt.replace('\\', '\\\\').replace('"""', '\\"\\"\\"')

        lines: list[str] = []
        lines.append(f'"""Agent Graph: {spec.agent.name} — Generated by Cortex Protocol v0.1"""')
        lines.append("")
        lines.append("from typing import Annotated, TypedDict")
        lines.append("")
        lines.append("from langchain_core.messages import AnyMessage, HumanMessage, SystemMessage")
        lines.append("from langchain_core.tools import tool")

        # Model-appropriate import
        model = spec.model.preferred
        if "claude" in model.lower() or "anthropic" in model.lower():
            lines.append("from langchain_anthropic import ChatAnthropic")
            llm_init = f'ChatAnthropic(model="{model}", temperature={spec.model.temperature})'
        elif "gemini" in model.lower():
            lines.append("from langchain_google_genai import ChatGoogleGenerativeAI")
            llm_init = f'ChatGoogleGenerativeAI(model="{model}", temperature={spec.model.temperature})'
        else:
            lines.append("from langchain_openai import ChatOpenAI")
            llm_init = f'ChatOpenAI(model="{model}", temperature={spec.model.temperature})'

        lines.append("from langgraph.graph import StateGraph, START, END")
        lines.append("from langgraph.graph.message import add_messages")
        lines.append("from langgraph.prebuilt import ToolNode")
        lines.append("from pydantic import BaseModel, Field")
        lines.append("")
        lines.append("")
        lines.append("# ── State ────────────────────────────────────────────────────────────")
        lines.append("")
        lines.append("class AgentState(TypedDict):")
        lines.append("    messages: Annotated[list[AnyMessage], add_messages]")
        lines.append("")
        lines.append("")
        lines.append("# ── Tools ────────────────────────────────────────────────────────────")
        lines.append("")

        tool_names: list[str] = []
        for t in spec.tools:
            func_name = _to_snake(t.name)
            tool_names.append(func_name)

            # Build Pydantic input schema if parameters exist
            if t.parameters.properties:
                lines.append(f"class {_to_pascal(t.name)}Input(BaseModel):")
                for pname, pschema in t.parameters.properties.items():
                    ptype = _json_type_to_python(pschema)
                    desc = pschema.get("description", t.description) if isinstance(pschema, dict) else t.description
                    lines.append(f'    {pname}: {ptype} = Field(description="{desc}")')
                lines.append("")
                lines.append("")
                args_schema = f', args_schema={_to_pascal(t.name)}Input'
            else:
                args_schema = ""

            # Build function signature
            params = ", ".join(
                f"{pname}: {_json_type_to_python(pschema)}"
                for pname, pschema in t.parameters.properties.items()
            )

            lines.append(f'@tool("{t.name}"{args_schema})')
            lines.append(f"def {func_name}({params}) -> str:")
            lines.append(f'    """{t.description}"""')
            lines.append(f"    # TODO: Implement {t.name}")
            lines.append(f'    return "{t.name} called"')
            lines.append("")
            lines.append("")

        tools_list_str = ", ".join(tool_names)
        lines.append(f"tools = [{tools_list_str}]")
        lines.append("")

        # Human-in-the-loop comment for approval-required tools
        if spec.policies.require_approval:
            approval_tools = ", ".join(f'"{_to_snake(t)}"' for t in spec.policies.require_approval)
            lines.append(f"# Human-in-the-loop: these tools require approval before execution")
            lines.append(f"# interrupt_before = [{approval_tools}]")
            lines.append("")

        lines.append("")
        lines.append("# ── LLM ─────────────────────────────────────────────────────────────")
        lines.append("")
        lines.append(f'SYSTEM_PROMPT = """{prompt_escaped}"""')
        lines.append("")
        lines.append(f"llm = {llm_init}")
        lines.append("llm_with_tools = llm.bind_tools(tools)")
        lines.append("")
        lines.append("")
        lines.append("# ── Nodes ────────────────────────────────────────────────────────────")
        lines.append("")
        lines.append("def agent_node(state: AgentState) -> AgentState:")
        lines.append('    """Main agent node — calls LLM with tools."""')
        lines.append('    messages = [SystemMessage(content=SYSTEM_PROMPT)] + state["messages"]')
        lines.append("    response = llm_with_tools.invoke(messages)")
        lines.append('    return {"messages": [response]}')
        lines.append("")
        lines.append("")
        lines.append("def should_continue(state: AgentState) -> str:")
        lines.append('    """Route to tools or end based on last message."""')
        lines.append('    last = state["messages"][-1]')
        lines.append('    if hasattr(last, "tool_calls") and last.tool_calls:')
        lines.append('        return "tools"')
        lines.append("    return END")
        lines.append("")
        lines.append("")
        lines.append("# ── Graph ────────────────────────────────────────────────────────────")
        lines.append("")
        lines.append("tool_node = ToolNode(tools)")
        lines.append("")
        lines.append("graph = StateGraph(AgentState)")
        lines.append('graph.add_node("agent", agent_node)')
        lines.append('graph.add_node("tools", tool_node)')
        lines.append("")
        lines.append('graph.add_edge(START, "agent")')
        lines.append('graph.add_conditional_edges("agent", should_continue, {"tools": "tools", END: END})')
        lines.append('graph.add_edge("tools", "agent")')
        lines.append("")
        lines.append("app = graph.compile()")
        lines.append("")
        lines.append("")
        lines.append("# ── Run ──────────────────────────────────────────────────────────────")
        lines.append("")
        lines.append('if __name__ == "__main__":')
        lines.append('    result = app.invoke({"messages": [HumanMessage(content="Hello, what can you do?")]})')
        lines.append('    for msg in result["messages"]:')
        lines.append('        print(f"{msg.type}: {msg.content}")')
        lines.append("")

        return OutputFile(
            path="agent_graph.py",
            content="\n".join(lines),
            description="LangGraph StateGraph with agent node and tool routing",
        )

    def _generate_requirements(self, spec: AgentSpec) -> OutputFile:
        model = spec.model.preferred
        if "claude" in model.lower() or "anthropic" in model.lower():
            extra = "langchain-anthropic>=0.3\n"
        elif "gemini" in model.lower():
            extra = "langchain-google-genai>=2.0\n"
        else:
            extra = "langchain-openai>=0.3\n"

        return OutputFile(
            path="requirements.txt",
            content=f"langgraph>=0.2\nlangchain-core>=0.3\n{extra}",
            description="Python dependencies",
        )

    def _generate_test(self, spec: AgentSpec) -> OutputFile:
        lines: list[str] = []
        lines.append(f'"""Tests for {spec.agent.name} graph — Generated by Cortex Protocol v0.1"""')
        lines.append("")
        lines.append("from agent_graph import app, tools, SYSTEM_PROMPT, AgentState")
        lines.append("")
        lines.append("")
        lines.append("def test_graph_compiles():")
        lines.append("    assert app is not None")
        lines.append("")
        lines.append("")
        lines.append("def test_system_prompt_present():")
        lines.append("    assert len(SYSTEM_PROMPT) > 0")
        lines.append(f'    assert "{spec.agent.name}" in SYSTEM_PROMPT')
        lines.append("")
        lines.append("")
        lines.append("def test_tools_registered():")
        lines.append(f"    assert len(tools) == {len(spec.tools)}")
        lines.append("    tool_names = {t.name for t in tools}")
        for t in spec.tools:
            lines.append(f'    assert "{t.name}" in tool_names')
        lines.append("")
        lines.append("")
        lines.append("def test_state_schema():")
        lines.append('    """Verify the state schema has the expected structure."""')
        lines.append('    assert "messages" in AgentState.__annotations__')
        lines.append("")

        return OutputFile(
            path="test_graph.py",
            content="\n".join(lines),
            description="Test stubs for the LangGraph agent",
        )


def _to_snake(name: str) -> str:
    return name.lower().replace("-", "_").replace(" ", "_")


def _to_pascal(name: str) -> str:
    return "".join(w.capitalize() for w in name.replace("-", " ").replace("_", " ").split())


def _json_type_to_python(schema: dict) -> str:
    type_map = {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "array": "list",
        "object": "dict",
    }
    t = schema.get("type", "string") if isinstance(schema, dict) else "str"
    return type_map.get(t, "str")
