"""OpenAI Agent SDK compilation target."""

from __future__ import annotations

import ast

from ..compiler import compile_system_prompt
from ..models import AgentSpec
from .base import CompilationTarget, OutputFile


class OpenAISDKTarget(CompilationTarget):
    name = "openai-sdk"
    description = "Runnable Python project using the OpenAI Agent SDK"

    def compile(self, spec: AgentSpec) -> list[OutputFile]:
        return [
            self._generate_agent(spec),
            self._generate_requirements(spec),
            self._generate_test(spec),
        ]

    def _generate_agent(self, spec: AgentSpec) -> OutputFile:
        prompt = compile_system_prompt(spec, "gpt-4o")
        prompt_escaped = prompt.replace('\\', '\\\\').replace('"""', '\\"\\"\\"')

        lines: list[str] = []
        lines.append(f'"""Agent: {spec.agent.name} — Generated by Cortex Protocol v0.1"""')
        lines.append("")
        lines.append("from agents import Agent, Runner, function_tool")
        lines.append("")

        if spec.policies.require_approval:
            tools = ", ".join(spec.policies.require_approval)
            lines.append(f"# NOTE: Tools requiring human approval: {tools}")
            lines.append("")

        lines.append("")
        lines.append("# ── Tool Definitions ─────────────────────────────────────────────────")
        lines.append("")

        tool_func_names: list[str] = []
        for tool in spec.tools:
            func_name = _to_snake(tool.name)
            tool_func_names.append(func_name)

            # Build parameter signature
            param_parts = []
            for pname, pschema in tool.parameters.properties.items():
                ptype = _json_type_to_python(pschema)
                if pname in tool.parameters.required:
                    param_parts.append(f"{pname}: {ptype}")
                else:
                    param_parts.append(f"{pname}: {ptype} = None")

            sig = ", ".join(param_parts)

            lines.append("@function_tool")
            lines.append(f"def {func_name}({sig}) -> str:")
            lines.append(f'    """{tool.description}"""')
            lines.append(f"    # TODO: Implement {tool.name}")
            lines.append(f'    return "{tool.name} called"')
            lines.append("")
            lines.append("")

        # Escalation handoff
        if spec.policies.escalation.trigger:
            target_name = spec.policies.escalation.target or "human-escalation"
            lines.append("# Escalation handoff")
            lines.append("escalation_agent = Agent(")
            lines.append(f'    name="{target_name}",')
            lines.append(f'    instructions="Handle escalated requests from {spec.agent.name}.",')
            lines.append(")")
            lines.append("")
            lines.append("")

        lines.append("# ── Agent Definition ─────────────────────────────────────────────────")
        lines.append("")
        lines.append(f'SYSTEM_PROMPT = """{prompt_escaped}"""')
        lines.append("")

        tools_list = ", ".join(tool_func_names)
        lines.append("agent = Agent(")
        lines.append(f'    name="{spec.agent.name}",')
        lines.append("    instructions=SYSTEM_PROMPT,")
        lines.append(f"    tools=[{tools_list}],")
        lines.append(")")
        lines.append("")
        lines.append("")
        lines.append("# ── Run ─────────────────────────────────────────────────────────────")
        lines.append("")
        lines.append('if __name__ == "__main__":')
        lines.append("    import asyncio")
        lines.append("")
        lines.append("    async def main():")
        lines.append('        result = await Runner.run(agent, input="Hello, what can you do?")')
        lines.append("        print(result.final_output)")
        lines.append("")
        lines.append("    asyncio.run(main())")
        lines.append("")

        return OutputFile(
            path="agent.py",
            content="\n".join(lines),
            description="OpenAI Agent SDK agent with tool definitions",
        )

    def _generate_requirements(self, spec: AgentSpec) -> OutputFile:
        return OutputFile(
            path="requirements.txt",
            content="openai-agents>=0.1\nopenai>=1.0\n",
            description="Python dependencies",
        )

    def _generate_test(self, spec: AgentSpec) -> OutputFile:
        lines: list[str] = []
        lines.append(f'"""Tests for {spec.agent.name} — Generated by Cortex Protocol v0.1"""')
        lines.append("")
        lines.append("from agent import agent")
        lines.append("")
        lines.append("")
        lines.append("def test_agent_name():")
        lines.append(f'    assert agent.name == "{spec.agent.name}"')
        lines.append("")
        lines.append("")
        lines.append("def test_agent_has_instructions():")
        lines.append("    assert len(agent.instructions) > 0")
        lines.append("")
        lines.append("")
        lines.append("def test_agent_tools_registered():")
        if spec.tools:
            for t in spec.tools:
                func_name = _to_snake(t.name)
                lines.append(f'    assert any(t.__name__ == "{func_name}" for t in agent.tools)')
        else:
            lines.append("    pass  # No tools defined")
        lines.append("")

        return OutputFile(
            path="test_agent.py",
            content="\n".join(lines),
            description="Test stubs for the generated agent",
        )


def _to_snake(name: str) -> str:
    return name.lower().replace("-", "_").replace(" ", "_")


def _json_type_to_python(schema: dict) -> str:
    type_map = {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "array": "list",
        "object": "dict",
    }
    t = schema.get("type", "string") if isinstance(schema, dict) else "str"
    return type_map.get(t, "str")
