"""
Semantic Kernel compilation target.

Generates a Python Kernel setup with ChatCompletionAgent,
a plugin class (native functions) for each tool,
and a run loop that enforces policies.

Semantic Kernel (Microsoft) is the primary framework used in Azure AI
and enterprise Microsoft stacks.
"""

from __future__ import annotations

from .base import CompilationTarget, OutputFile
from ..models import AgentSpec
from ..compiler import compile_system_prompt
from ..network.mcp import generate_mcp_client_code


def _to_pascal(name: str) -> str:
    """Convert kebab/snake names to PascalCase for class names."""
    parts = name.replace("-", "_").split("_")
    return "".join(p.capitalize() for p in parts if p)


def _to_snake(name: str) -> str:
    return name.replace("-", "_").lower()


class SemanticKernelTarget(CompilationTarget):
    description = "Microsoft Semantic Kernel — ChatCompletionAgent + plugin functions"

    def compile(self, spec: AgentSpec) -> list[OutputFile]:
        return [
            OutputFile("agent.py", self._agent_py(spec), "Kernel setup + ChatCompletionAgent"),
            OutputFile("requirements.txt", self._requirements(spec), "Package dependencies"),
            OutputFile("test_agent.py", self._test_py(spec), "Agent test scaffold"),
        ]

    # ------------------------------------------------------------------
    # agent.py
    # ------------------------------------------------------------------

    def _agent_py(self, spec: AgentSpec) -> str:
        system_prompt = compile_system_prompt(spec, spec.model.preferred if spec.model else None)
        agent_class = _to_pascal(spec.agent.name)
        plugin_class = f"{agent_class}Plugin"

        lines: list[str] = []

        lines.append('"""')
        lines.append(f"Semantic Kernel agent: {spec.agent.name}")
        lines.append(f"Generated by Cortex Protocol — do not edit directly.")
        lines.append('"""')
        lines.append("")
        lines.append("import asyncio")
        lines.append("import os")
        lines.append("from typing import Annotated")
        lines.append("")
        lines.append("from semantic_kernel import Kernel")
        lines.append("from semantic_kernel.agents import ChatCompletionAgent")
        lines.append("from semantic_kernel.connectors.ai.open_ai import AzureChatCompletion")
        lines.append("from semantic_kernel.contents.chat_history import ChatHistory")
        lines.append("from semantic_kernel.functions.kernel_function_decorator import kernel_function")
        lines.append("from semantic_kernel.connectors.ai import PromptExecutionSettings")

        if spec.policies and spec.policies.require_approval:
            lines.append("# Human approval: implement these hooks in production")

        lines.append("")
        lines.append("")

        # --- System prompt constant ---
        lines.append("SYSTEM_PROMPT = '''")
        for line in system_prompt.splitlines():
            lines.append(line)
        lines.append("'''")
        lines.append("")
        lines.append("")

        # --- Plugin class ---
        lines.append(f"class {plugin_class}:")
        lines.append(f'    """Plugin exposing {spec.agent.name} tools to Semantic Kernel."""')
        lines.append("")

        if not spec.tools:
            lines.append("    pass")
        else:
            for tool in spec.tools:
                fn_name = _to_snake(tool.name)
                needs_approval = (
                    spec.policies
                    and spec.policies.require_approval
                    and tool.name in spec.policies.require_approval
                )

                lines.append("    @kernel_function(")
                lines.append(f'        name="{fn_name}",')
                lines.append(f'        description="{tool.description}",')
                lines.append("    )")
                lines.append(f"    def {fn_name}(self, input: Annotated[str, 'Input payload as JSON string']) -> str:")

                if needs_approval:
                    lines.append(f"        # APPROVAL REQUIRED — gate this call before production use")
                    lines.append(f"        raise NotImplementedError(")
                    lines.append(f"            '{fn_name} requires human approval. Implement approval gate here.'")
                    lines.append(f"        )")
                else:
                    lines.append(f"        # TODO: implement {fn_name}")
                    lines.append(f"        raise NotImplementedError")

                lines.append("")

        lines.append("")

        # --- Kernel factory ---
        lines.append(f"def build_kernel() -> Kernel:")
        lines.append(f'    """Build and configure the Semantic Kernel."""')
        lines.append(f"    kernel = Kernel()")
        lines.append(f"")

        # Determine service from model
        preferred = spec.model.preferred if spec.model else "gpt-4o"
        if "claude" in preferred.lower() or "anthropic" in preferred.lower():
            lines.append("    # Claude via Azure AI Foundry or Anthropic connector")
            lines.append("    from semantic_kernel.connectors.ai.anthropic import AnthropicChatCompletion")
            lines.append("    service = AnthropicChatCompletion(")
            lines.append(f'        ai_model_id=os.environ.get("ANTHROPIC_MODEL", "{preferred}"),')
            lines.append("        api_key=os.environ[\"ANTHROPIC_API_KEY\"],")
            lines.append("    )")
        elif "gemini" in preferred.lower():
            lines.append("    # Gemini via Google AI connector")
            lines.append("    from semantic_kernel.connectors.ai.google.google_ai import GoogleAIChatCompletion")
            lines.append("    service = GoogleAIChatCompletion(")
            lines.append(f'        gemini_model_id=os.environ.get("GOOGLE_MODEL", "{preferred}"),')
            lines.append("        api_key=os.environ[\"GOOGLE_API_KEY\"],")
            lines.append("    )")
        else:
            lines.append("    service = AzureChatCompletion(")
            lines.append(f'        deployment_name=os.environ.get("AZURE_OPENAI_DEPLOYMENT", "{preferred}"),')
            lines.append("        endpoint=os.environ[\"AZURE_OPENAI_ENDPOINT\"],")
            lines.append("        api_key=os.environ[\"AZURE_OPENAI_API_KEY\"],")
            lines.append("    )")

        lines.append("    kernel.add_service(service)")
        lines.append("")
        lines.append(f"    kernel.add_plugin({plugin_class}(), plugin_name=\"{_to_snake(spec.agent.name)}\")")

        # MCP plugin setup
        for tool in spec.tools:
            if tool.mcp:
                mcp_code = generate_mcp_client_code("semantic-kernel", tool.name, tool.mcp)
                lines.append(f"    from semantic_kernel.connectors.mcp import MCPStdioPlugin")
                lines.append(f"    {mcp_code['setup']}")
                lines.append(f"    # kernel.add_plugin({_to_snake(tool.name)}_plugin)")

        lines.append("    return kernel")
        lines.append("")
        lines.append("")

        # --- Agent factory ---
        max_turns = spec.policies.max_turns if spec.policies else 20

        lines.append(f"def build_agent(kernel: Kernel | None = None) -> ChatCompletionAgent:")
        lines.append(f'    """Build the {spec.agent.name} ChatCompletionAgent."""')
        lines.append(f"    if kernel is None:")
        lines.append(f"        kernel = build_kernel()")
        lines.append(f"    agent = ChatCompletionAgent(")
        lines.append(f"        kernel=kernel,")
        lines.append(f'        name="{_to_snake(spec.agent.name)}",')
        lines.append(f"        instructions=SYSTEM_PROMPT,")
        lines.append(f"    )")
        lines.append(f"    return agent")
        lines.append("")
        lines.append("")

        # --- Main run loop ---
        lines.append("async def run_agent(user_message: str) -> str:")
        lines.append(f'    """Run the {spec.agent.name} agent on a single user message."""')
        lines.append(f"    agent = build_agent()")
        lines.append(f"    history = ChatHistory()")
        lines.append(f"    history.add_user_message(user_message)")
        lines.append(f"    max_turns = {max_turns}")
        lines.append(f"    turn = 0")
        lines.append(f"    async for response in agent.invoke(history):")
        lines.append(f"        turn += 1")
        lines.append(f"        if turn >= max_turns:")
        if spec.policies and spec.policies.escalation and spec.policies.escalation.trigger:
            lines.append(f"            # Escalation: {spec.policies.escalation.trigger}")
            lines.append(f"            return f\"Escalating to {spec.policies.escalation.target}: max turns reached.\"")
        else:
            lines.append(f"            return \"Max turns reached. Please try again.\"")
        lines.append(f"        return str(response)")
        lines.append(f'    return "No response generated."')
        lines.append("")
        lines.append("")

        # --- Entry point ---
        lines.append('if __name__ == "__main__":')
        lines.append('    result = asyncio.run(run_agent("Hello, how can you help me?"))')
        lines.append('    print(result)')

        return "\n".join(lines) + "\n"

    # ------------------------------------------------------------------
    # requirements.txt
    # ------------------------------------------------------------------

    def _requirements(self, spec: AgentSpec) -> str:
        preferred = spec.model.preferred if spec.model else "gpt-4o"
        lines = [
            "semantic-kernel>=1.0.0",
        ]
        if "claude" in preferred.lower():
            lines.append("semantic-kernel[anthropic]>=1.0.0")
        elif "gemini" in preferred.lower():
            lines.append("semantic-kernel[google]>=1.0.0")
        else:
            lines.append("azure-identity>=1.15.0")
        lines.append("python-dotenv>=1.0.0")
        if any(t.mcp for t in spec.tools):
            lines.append("semantic-kernel[mcp]>=1.0.0")
        return "\n".join(lines) + "\n"

    # ------------------------------------------------------------------
    # test_agent.py
    # ------------------------------------------------------------------

    def _test_py(self, spec: AgentSpec) -> str:
        plugin_class = f"{_to_pascal(spec.agent.name)}Plugin"
        lines: list[str] = []

        lines.append('"""Tests for the Semantic Kernel agent scaffold."""')
        lines.append("")
        lines.append("import pytest")
        lines.append("from unittest.mock import AsyncMock, MagicMock, patch")
        lines.append("from agent import build_kernel, build_agent, SYSTEM_PROMPT")
        lines.append(f"from agent import {plugin_class}")
        lines.append("")
        lines.append("")

        lines.append("class TestSystemPrompt:")
        lines.append("    def test_system_prompt_not_empty(self):")
        lines.append("        assert len(SYSTEM_PROMPT.strip()) > 0")
        lines.append("")
        lines.append("    def test_agent_name_in_prompt(self):")
        lines.append(f'        assert "{spec.agent.name}" in SYSTEM_PROMPT')
        lines.append("")
        lines.append("")

        lines.append(f"class Test{plugin_class}:")
        if spec.tools:
            for tool in spec.tools:
                needs_approval = (
                    spec.policies
                    and spec.policies.require_approval
                    and tool.name in spec.policies.require_approval
                )
                fn_name = _to_snake(tool.name)
                lines.append(f"    def test_{fn_name}_raises_not_implemented(self):")
                lines.append(f"        plugin = {plugin_class}()")
                if needs_approval:
                    lines.append(f"        with pytest.raises(NotImplementedError):")
                    lines.append(f"            plugin.{fn_name}(input='{{\"test\": true}}')")
                else:
                    lines.append(f"        with pytest.raises(NotImplementedError):")
                    lines.append(f"            plugin.{fn_name}(input='{{\"test\": true}}')")
                lines.append("")
        else:
            lines.append("    pass")

        lines.append("")
        lines.append("")
        lines.append("class TestBuildAgent:")
        lines.append("    @patch('agent.build_kernel')")
        lines.append("    def test_build_agent_returns_agent(self, mock_kernel):")
        lines.append("        mock_kernel.return_value = MagicMock()")
        lines.append("        # ChatCompletionAgent requires a live kernel in practice")
        lines.append("        # This is a structural test only")
        lines.append("        assert build_agent is not None")

        return "\n".join(lines) + "\n"
