"""
CI workflow generators for Cortex Protocol.

Generates GitHub Actions workflows that validate, lint, and compile
agent specs on every pull request and push.
"""

from __future__ import annotations


def generate_github_action(
    spec_path: str = "agent.yaml",
    drift_spec: str | None = None,
    drift_threshold: float | None = None,
    audit_log_pattern: str | None = None,
) -> str:
    """
    Generate a GitHub Actions workflow for Cortex Protocol.

    The workflow:
    - Runs on every PR and push to main
    - Validates the spec schema
    - Lints governance quality (fails on errors)
    - Compiles to all 6 targets as a dry-run verification

    Args:
        spec_path: Path to the agent spec file relative to the repo root.
    """
    lines: list[str] = []

    lines.append("# Cortex Protocol — Agent Spec CI")
    lines.append("# Generated by: cortex-protocol generate-ci")
    lines.append("# Validates, lints, and compiles your agent spec on every PR.")
    lines.append("")
    lines.append("name: Cortex Protocol")
    lines.append("")
    lines.append("on:")
    lines.append("  pull_request:")
    lines.append("    paths:")
    lines.append(f"      - '{spec_path}'")
    lines.append("      - '.github/workflows/cortex-protocol.yml'")
    lines.append("  push:")
    lines.append("    branches:")
    lines.append("      - main")
    lines.append("    paths:")
    lines.append(f"      - '{spec_path}'")
    lines.append("")
    lines.append("jobs:")
    lines.append("  validate-and-lint:")
    lines.append("    name: Validate + Lint Agent Spec")
    lines.append("    runs-on: ubuntu-latest")
    lines.append("")
    lines.append("    steps:")
    lines.append("      - uses: actions/checkout@v4")
    lines.append("")
    lines.append("      - uses: actions/setup-python@v5")
    lines.append("        with:")
    lines.append("          python-version: '3.12'")
    lines.append("          cache: 'pip'")
    lines.append("")
    lines.append("      - name: Install cortex-protocol")
    lines.append("        run: pip install cortex-protocol")
    lines.append("")
    lines.append("      - name: Validate spec schema")
    lines.append(f"        run: cortex-protocol validate {spec_path}")
    lines.append("")
    lines.append("      - name: Lint governance quality")
    lines.append(f"        run: cortex-protocol lint {spec_path} --fail-on error")
    lines.append("        # Fails the build if any ERROR-severity lint rules are violated.")
    lines.append("        # Change to --fail-on warning to enforce stricter governance.")
    lines.append("")
    lines.append("      - name: Compile to all targets (dry run)")
    lines.append(f"        run: cortex-protocol compile {spec_path} --target all --output /tmp/cortex-build")
    lines.append("")
    lines.append("      - name: Upload compiled artifacts")
    lines.append("        uses: actions/upload-artifact@v4")
    lines.append("        with:")
    lines.append("          name: cortex-compiled-${{ github.sha }}")
    lines.append("          path: /tmp/cortex-build/")
    lines.append("          retention-days: 7")
    lines.append("        if: github.event_name == 'push'")
    lines.append("")
    lines.append("  lint-score-comment:")
    lines.append("    name: Post Governance Score to PR")
    lines.append("    runs-on: ubuntu-latest")
    lines.append("    if: github.event_name == 'pull_request'")
    lines.append("    permissions:")
    lines.append("      pull-requests: write")
    lines.append("")
    lines.append("    steps:")
    lines.append("      - uses: actions/checkout@v4")
    lines.append("")
    lines.append("      - uses: actions/setup-python@v5")
    lines.append("        with:")
    lines.append("          python-version: '3.12'")
    lines.append("")
    lines.append("      - name: Install cortex-protocol")
    lines.append("        run: pip install cortex-protocol")
    lines.append("")
    lines.append("      - name: Generate lint report")
    lines.append(f"        run: cortex-protocol lint {spec_path} --format json > /tmp/lint_report.json")
    lines.append("        continue-on-error: true")
    lines.append("")
    lines.append("      - name: Post score comment")
    lines.append("        uses: actions/github-script@v7")
    lines.append("        with:")
    lines.append("          script: |")
    lines.append("            const fs = require('fs');")
    lines.append("            const report = JSON.parse(fs.readFileSync('/tmp/lint_report.json', 'utf8'));")
    lines.append("            const gradeEmoji = {A: '🟢', B: '🟢', C: '🟡', D: '🟠', F: '🔴'};")
    lines.append("            const emoji = gradeEmoji[report.grade] || '⚪';")
    lines.append("            const lines = report.results")
    lines.append(r"              .map(r => `| ${r.passed ? '✓' : '✗'} | \`${r.rule}\` | ${r.severity} | ${r.message} |`);")
    lines.append("            const body = [")
    lines.append("              `## ${emoji} Cortex Protocol — Governance Score: ${report.score}/100 (Grade: ${report.grade})`,")
    lines.append("              '',")
    lines.append("              '| Status | Rule | Severity | Message |',")
    lines.append("              '|--------|------|----------|---------|',")
    lines.append("              ...lines,")
    lines.append("            ].join('\\n');")
    lines.append("            github.rest.issues.createComment({")
    lines.append("              issue_number: context.issue.number,")
    lines.append("              owner: context.repo.owner,")
    lines.append("              repo: context.repo.repo,")
    lines.append("              body")
    lines.append("            });")

    # Optional drift-check job
    if drift_spec and drift_threshold is not None:
        log_pattern = audit_log_pattern or "./logs/audit_*.jsonl"
        lines.append("")
        lines.append("  drift:")
        lines.append("    name: Drift Check")
        lines.append("    runs-on: ubuntu-latest")
        lines.append("    needs: validate-and-lint")
        lines.append("    if: github.event_name == 'push'")
        lines.append("")
        lines.append("    steps:")
        lines.append("      - uses: actions/checkout@v4")
        lines.append("")
        lines.append("      - uses: actions/setup-python@v5")
        lines.append("        with:")
        lines.append("          python-version: '3.12'")
        lines.append("")
        lines.append("      - name: Install cortex-protocol")
        lines.append("        run: pip install cortex-protocol")
        lines.append("")
        lines.append("      - name: Run drift check")
        lines.append(f"        run: cortex-protocol drift-check {drift_spec} {log_pattern} --fail-on {drift_threshold}")

    return "\n".join(lines) + "\n"


def generate_composite_action(
    spec_input: str = "spec",
    fail_on_lint: str = "error",
) -> str:
    """Generate a reusable GitHub Action action.yml."""
    lines: list[str] = []
    lines.append("name: 'Cortex Protocol'")
    lines.append("description: 'Validate, lint, and drift-check an agent spec'")
    lines.append("")
    lines.append("inputs:")
    lines.append(f"  {spec_input}:")
    lines.append("    description: 'Path to the agent spec file'")
    lines.append("    required: true")
    lines.append("    default: 'agent.yaml'")
    lines.append("  fail-on-lint:")
    lines.append("    description: 'Lint severity that fails the build'")
    lines.append("    required: false")
    lines.append(f"    default: '{fail_on_lint}'")
    lines.append("  drift-threshold:")
    lines.append("    description: 'Minimum compliance score (0.0-1.0) for drift check'")
    lines.append("    required: false")
    lines.append("    default: ''")
    lines.append("  audit-log:")
    lines.append("    description: 'Path or glob pattern for audit log files'")
    lines.append("    required: false")
    lines.append("    default: './logs/audit_*.jsonl'")
    lines.append("")
    lines.append("runs:")
    lines.append("  using: 'composite'")
    lines.append("  steps:")
    lines.append("    - name: Install cortex-protocol")
    lines.append("      shell: bash")
    lines.append("      run: pip install cortex-protocol")
    lines.append("")
    lines.append("    - name: Validate spec")
    lines.append("      shell: bash")
    lines.append(f"      run: cortex-protocol validate ${{{{ inputs.{spec_input} }}}}")
    lines.append("")
    lines.append("    - name: Lint spec")
    lines.append("      shell: bash")
    lines.append(f"      run: cortex-protocol lint ${{{{ inputs.{spec_input} }}}} --fail-on ${{{{ inputs.fail-on-lint }}}}")
    lines.append("")
    lines.append("    - name: Drift check")
    lines.append("      shell: bash")
    lines.append("      if: inputs.drift-threshold != ''")
    lines.append(f"      run: cortex-protocol drift-check ${{{{ inputs.{spec_input} }}}} ${{{{ inputs.audit-log }}}} --fail-on ${{{{ inputs.drift-threshold }}}}")
    lines.append("")
    return "\n".join(lines) + "\n"
