"""A2A (Agent-to-Agent) protocol support.

Generates A2A-compatible agent cards and handler scaffolds per Google's
Agent-to-Agent protocol specification. An A2A "agent card" is a JSON-LD
document that describes what an agent can do, how to reach it, and what
skills it offers — the discovery layer for inter-agent communication.

Reference: https://google.github.io/A2A/

This module generates:
1. Agent Cards (JSON) — for registration in an A2A directory
2. Handler scaffolds — Python code that implements the A2A server interface
"""

from __future__ import annotations

import json
from typing import Optional

from ..models import AgentSpec
from .models import NetworkSpec


# ---------------------------------------------------------------------------
# A2A Agent Card generation
# ---------------------------------------------------------------------------

def generate_a2a_card(
    spec: AgentSpec,
    url: str = "http://localhost:8000",
    version: str = "1.0.0",
) -> dict:
    """Generate an A2A agent card from a Cortex Protocol agent spec.

    The agent card is the discovery document that other agents use to
    find and communicate with this agent.

    Args:
        spec: Agent specification
        url: Base URL where the agent will be hosted
        version: Agent version string

    Returns:
        A2A agent card as a dict (JSON-serializable).
    """
    skills = []
    for tool in spec.tools:
        skill = {
            "id": tool.name,
            "name": tool.name,
            "description": tool.description,
            "tags": [tool.name.split("-")[0]] if "-" in tool.name else [tool.name],
        }
        if tool.parameters.properties:
            skill["inputSchema"] = {
                "type": "object",
                "properties": tool.parameters.properties,
                "required": tool.parameters.required,
            }
        if tool.mcp:
            skill["tags"].append("mcp")
            skill["extensions"] = {"mcp_server": tool.mcp}
        skills.append(skill)

    card = {
        "name": spec.agent.name,
        "description": spec.agent.description,
        "url": url,
        "version": version,
        "capabilities": {
            "streaming": False,
            "pushNotifications": False,
            "stateTransitionHistory": True,
        },
        "skills": skills,
        "defaultInputModes": ["text/plain"],
        "defaultOutputModes": ["text/plain"],
    }

    # Add metadata if present
    if spec.metadata:
        card["extensions"] = {
            "cortex_protocol": {
                "owner": spec.metadata.owner,
                "tags": spec.metadata.tags,
                "compliance": spec.metadata.compliance,
            }
        }

    return card


def generate_a2a_card_json(spec: AgentSpec, **kwargs) -> str:
    """Generate an A2A agent card as a JSON string."""
    return json.dumps(generate_a2a_card(spec, **kwargs), indent=2)


# ---------------------------------------------------------------------------
# A2A handler scaffold generation
# ---------------------------------------------------------------------------

def generate_a2a_handler(spec: AgentSpec, framework: str = "fastapi") -> str:
    """Generate an A2A-compatible server handler scaffold.

    Generates a Python file that implements the A2A JSON-RPC interface,
    responds to tasks/send and tasks/get, and dispatches to agent logic.

    Args:
        spec: Agent specification
        framework: Web framework to use (fastapi, flask)

    Returns:
        Generated Python code as a string.
    """
    if framework == "flask":
        return _gen_flask_handler(spec)
    return _gen_fastapi_handler(spec)


def _gen_fastapi_handler(spec: AgentSpec) -> str:
    """Generate a FastAPI-based A2A handler."""
    agent_name = spec.agent.name
    snake_name = agent_name.lower().replace("-", "_")
    card = generate_a2a_card(spec)
    card_json = json.dumps(card, indent=4)
    # Indent card_json for embedding
    card_indented = "\n".join(f"    {line}" if i > 0 else f"    {line}"
                              for i, line in enumerate(card_json.split("\n")))

    lines: list[str] = []
    lines.append(f'"""A2A handler for {agent_name}')
    lines.append(f'Generated by Cortex Protocol — implements Google A2A protocol.')
    lines.append(f'"""')
    lines.append("")
    lines.append("import uuid")
    lines.append("from datetime import datetime, timezone")
    lines.append("")
    lines.append("from fastapi import FastAPI, Request")
    lines.append("from fastapi.responses import JSONResponse")
    lines.append("")
    lines.append("")
    lines.append(f'app = FastAPI(title="{agent_name} A2A Server")')
    lines.append("")
    lines.append("")
    lines.append("# ── Agent Card ────────────────────────────────────────────────────────")
    lines.append("")
    lines.append("AGENT_CARD = " + card_json)
    lines.append("")
    lines.append("")
    lines.append("# ── In-memory task store ────────────────────────────────────────────")
    lines.append("")
    lines.append("tasks: dict[str, dict] = {}")
    lines.append("")
    lines.append("")
    lines.append("# ── A2A Endpoints ─────────────────────────────────────────────────────")
    lines.append("")
    lines.append('@app.get("/.well-known/agent.json")')
    lines.append("async def agent_card():")
    lines.append('    """A2A agent card discovery endpoint."""')
    lines.append("    return JSONResponse(AGENT_CARD)")
    lines.append("")
    lines.append("")
    lines.append('@app.post("/a2a")')
    lines.append("async def a2a_endpoint(request: Request):")
    lines.append('    """A2A JSON-RPC endpoint."""')
    lines.append("    body = await request.json()")
    lines.append('    method = body.get("method", "")')
    lines.append('    params = body.get("params", {})')
    lines.append('    rpc_id = body.get("id", str(uuid.uuid4()))')
    lines.append("")
    lines.append('    if method == "tasks/send":')
    lines.append("        return await handle_task_send(params, rpc_id)")
    lines.append('    elif method == "tasks/get":')
    lines.append("        return await handle_task_get(params, rpc_id)")
    lines.append('    elif method == "tasks/cancel":')
    lines.append("        return await handle_task_cancel(params, rpc_id)")
    lines.append("    else:")
    lines.append('        return JSONResponse({')
    lines.append('            "jsonrpc": "2.0",')
    lines.append('            "id": rpc_id,')
    lines.append('            "error": {"code": -32601, "message": f"Method not found: {method}"},')
    lines.append("        })")
    lines.append("")
    lines.append("")

    # Task send handler
    lines.append("async def handle_task_send(params: dict, rpc_id: str) -> JSONResponse:")
    lines.append('    """Handle tasks/send — create and run a task."""')
    lines.append('    task_id = params.get("id", str(uuid.uuid4()))')
    lines.append('    message = params.get("message", {})')
    lines.append('    input_text = ""')
    lines.append('    for part in message.get("parts", []):')
    lines.append('        if part.get("type") == "text":')
    lines.append('            input_text = part.get("text", "")')
    lines.append("")
    lines.append(f"    # TODO: Wire to your {agent_name} agent implementation")
    lines.append(f'    response_text = f"{agent_name} received: {{input_text}}"')
    lines.append("")
    lines.append("    task = {")
    lines.append('        "id": task_id,')
    lines.append('        "status": {"state": "completed"},')
    lines.append('        "artifacts": [{')
    lines.append('            "parts": [{"type": "text", "text": response_text}],')
    lines.append("        }],")
    lines.append("    }")
    lines.append("    tasks[task_id] = task")
    lines.append("")
    lines.append("    return JSONResponse({")
    lines.append('        "jsonrpc": "2.0",')
    lines.append('        "id": rpc_id,')
    lines.append('        "result": task,')
    lines.append("    })")
    lines.append("")
    lines.append("")

    # Task get handler
    lines.append("async def handle_task_get(params: dict, rpc_id: str) -> JSONResponse:")
    lines.append('    """Handle tasks/get — retrieve task status."""')
    lines.append('    task_id = params.get("id", "")')
    lines.append("    task = tasks.get(task_id)")
    lines.append("    if not task:")
    lines.append("        return JSONResponse({")
    lines.append('            "jsonrpc": "2.0",')
    lines.append('            "id": rpc_id,')
    lines.append('            "error": {"code": -32602, "message": f"Task not found: {task_id}"},')
    lines.append("        })")
    lines.append("    return JSONResponse({")
    lines.append('        "jsonrpc": "2.0",')
    lines.append('        "id": rpc_id,')
    lines.append('        "result": task,')
    lines.append("    })")
    lines.append("")
    lines.append("")

    # Task cancel handler
    lines.append("async def handle_task_cancel(params: dict, rpc_id: str) -> JSONResponse:")
    lines.append('    """Handle tasks/cancel — cancel a running task."""')
    lines.append('    task_id = params.get("id", "")')
    lines.append("    task = tasks.get(task_id)")
    lines.append("    if task:")
    lines.append('        task["status"]["state"] = "canceled"')
    lines.append("    return JSONResponse({")
    lines.append('        "jsonrpc": "2.0",')
    lines.append('        "id": rpc_id,')
    lines.append('        "result": task or {"id": task_id, "status": {"state": "canceled"}},')
    lines.append("    })")
    lines.append("")
    lines.append("")

    lines.append('if __name__ == "__main__":')
    lines.append("    import uvicorn")
    lines.append(f'    uvicorn.run(app, host="0.0.0.0", port=8000)')
    lines.append("")

    return "\n".join(lines)


def _gen_flask_handler(spec: AgentSpec) -> str:
    """Generate a Flask-based A2A handler (simpler alternative)."""
    agent_name = spec.agent.name
    card = generate_a2a_card(spec)
    card_json = json.dumps(card, indent=4)

    lines: list[str] = []
    lines.append(f'"""A2A handler for {agent_name} (Flask)')
    lines.append(f'Generated by Cortex Protocol."""')
    lines.append("")
    lines.append("import uuid")
    lines.append("from flask import Flask, request, jsonify")
    lines.append("")
    lines.append(f'app = Flask("{agent_name}")')
    lines.append("")
    lines.append("AGENT_CARD = " + card_json)
    lines.append("")
    lines.append("tasks = {}")
    lines.append("")
    lines.append("")
    lines.append('@app.route("/.well-known/agent.json")')
    lines.append("def agent_card():")
    lines.append("    return jsonify(AGENT_CARD)")
    lines.append("")
    lines.append("")
    lines.append('@app.route("/a2a", methods=["POST"])')
    lines.append("def a2a_endpoint():")
    lines.append("    body = request.json")
    lines.append('    method = body.get("method", "")')
    lines.append('    params = body.get("params", {})')
    lines.append('    rpc_id = body.get("id", str(uuid.uuid4()))')
    lines.append("")
    lines.append('    if method == "tasks/send":')
    lines.append('        task_id = params.get("id", str(uuid.uuid4()))')
    lines.append(f'        response_text = f"{agent_name} received task {{task_id}}"')
    lines.append('        task = {"id": task_id, "status": {"state": "completed"},')
    lines.append('                "artifacts": [{"parts": [{"type": "text", "text": response_text}]}]}')
    lines.append("        tasks[task_id] = task")
    lines.append('        return jsonify({"jsonrpc": "2.0", "id": rpc_id, "result": task})')
    lines.append("")
    lines.append('    elif method == "tasks/get":')
    lines.append('        task = tasks.get(params.get("id"))')
    lines.append("        if task:")
    lines.append('            return jsonify({"jsonrpc": "2.0", "id": rpc_id, "result": task})')
    lines.append('        return jsonify({"jsonrpc": "2.0", "id": rpc_id,')
    lines.append('                        "error": {"code": -32602, "message": "Not found"}})')
    lines.append("")
    lines.append('    return jsonify({"jsonrpc": "2.0", "id": rpc_id,')
    lines.append('                    "error": {"code": -32601, "message": "Method not found"}})')
    lines.append("")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    app.run(port=8000)")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Network-level A2A: generate cards for all agents
# ---------------------------------------------------------------------------

def generate_network_a2a_cards(
    network: NetworkSpec,
    agent_specs: dict[str, AgentSpec] | None = None,
    base_url: str = "http://localhost",
    base_port: int = 8000,
) -> dict[str, dict]:
    """Generate A2A agent cards for all agents in a network.

    Each agent gets a unique port starting from base_port.
    Returns dict of {agent_name: agent_card}.
    """
    names = network.agent_names()
    cards: dict[str, dict] = {}

    for i, name in enumerate(names):
        port = base_port + i
        url = f"{base_url}:{port}"

        if agent_specs and name in agent_specs and agent_specs[name]:
            card = generate_a2a_card(agent_specs[name], url=url)
        else:
            # Minimal card from network info
            card = {
                "name": name,
                "description": f"Agent in {network.name} network",
                "url": url,
                "version": "1.0.0",
                "capabilities": {
                    "streaming": False,
                    "pushNotifications": False,
                },
                "skills": [],
                "defaultInputModes": ["text/plain"],
                "defaultOutputModes": ["text/plain"],
            }

        # Add network routing info
        routes = network.get_routes_from(name)
        if routes:
            peers = []
            for route in routes:
                for to_name in route.to:
                    idx = names.index(to_name) if to_name in names else 0
                    peers.append({
                        "name": to_name,
                        "url": f"{base_url}:{base_port + idx}",
                        "condition": route.condition,
                    })
            card.setdefault("extensions", {})
            card["extensions"]["a2a_peers"] = peers

        cards[name] = card

    return cards
